// @ts-nocheck
export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: "{\"@context\":\"https://schema.org\",\"@type\":\"FAQPage\",\"mainEntity\":[{\"@type\":\"Question\",\"name\":\"What is Traffikora?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Traffikora is an AI marketing automation platform that publishes SEO content, social media posts, and AI engine optimization daily for local businesses — automatically.\"}},{\"@type\":\"Question\",\"name\":\"How does Traffikora work?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"You connect your accounts once. Traffikora's AI agents generate and publish content across your website, social media, and AI engines every day without any manual work.\"}},{\"@type\":\"Question\",\"name\":\"What platforms does Traffikora publish to?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Traffikora publishes to Google, WordPress, Facebook, Instagram, TikTok, YouTube, LinkedIn, X, and optimizes for AI engines including ChatGPT, Gemini, and Perplexity.\"}},{\"@type\":\"Question\",\"name\":\"How much does Traffikora cost?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Traffikora has a free plan with no credit card required. Paid plans start at $47/month for Starter, $97/month for Pro, $297/month for Agency, and $997/month for Enterprise.\"}},{\"@type\":\"Question\",\"name\":\"Does Traffikora work for my industry?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Traffikora works for 12+ local business industries including HVAC, dental, law firms, salons, restaurants, real estate, gyms, auto repair, med spas, plumbers, marketing agencies, and chiropractors.\"}},{\"@type\":\"Question\",\"name\":\"Is Traffikora HIPAA compliant for healthcare businesses?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"Traffikora generates informational marketing content. Healthcare businesses should review content before publishing to ensure compliance with their specific regulations.\"}}]}" }} />
      {children}
    </>
  )
}
