const fs = require('fs');
const path = require('path');
const base = 'C:\\Users\\randy\\traffikfuel\\src';

// Write ContentScore directly — no template literal nesting
const scoreLines = [
"// @ts-nocheck",
"",
"export function calculateContentScore(content, title, platform) {",
"  if (!content || !title) return { score: 0, breakdown: {} }",
"  platform = platform || 'blog'",
"  var words = content.split(/\\s+/).filter(Boolean)",
"  var wordCount = words.length",
"  var sentences = content.split(/[.!?]+/).filter(function(s) { return s.trim().length > 10 })",
"  var paragraphs = content.split(/\\n\\n+/).filter(function(p) { return p.trim().length > 20 })",
"  var lines = content.split('\\n')",
"  var breakdown = {}",
"",
"  if (platform === 'blog') {",
"    if (wordCount >= 1500) breakdown.wordCount = 20",
"    else if (wordCount >= 1200) breakdown.wordCount = 16",
"    else if (wordCount >= 900) breakdown.wordCount = 11",
"    else if (wordCount >= 600) breakdown.wordCount = 6",
"    else if (wordCount >= 300) breakdown.wordCount = 2",
"    else breakdown.wordCount = 0",
"",
"    var ts = 0",
"    if (title.length >= 40 && title.length <= 65) ts += 5",
"    else if (title.length >= 25) ts += 2",
"    if (/\\b\\d+\\b/.test(title)) ts += 4",
"    if (/\\b(ultimate|complete|proven|best|top|essential|powerful|expert|advanced|master|definitive|comprehensive)\\b/i.test(title)) ts += 4",
"    else if (/\\b(how|why|guide|tips|ways|steps|secrets|boost|improve|grow)\\b/i.test(title)) ts += 2",
"    if (/[?!]$/.test(title.trim())) ts += 2",
"    breakdown.titleQuality = Math.min(15, ts)",
"",
"    var headings = lines.filter(function(l) { return /^#{1,3}\\s.{5,}/.test(l.trim()) || /^\\*\\*[A-Z].{5,}\\*\\*/.test(l.trim()) })",
"    breakdown.headings = headings.length >= 5 ? 12 : headings.length >= 3 ? 8 : headings.length >= 1 ? 4 : 0",
"",
"    var listItems = lines.filter(function(l) { return /^[-*]\\s.{5,}/.test(l.trim()) || /^\\d+\\.\\s.{5,}/.test(l.trim()) })",
"    breakdown.lists = listItems.length >= 6 ? 8 : listItems.length >= 3 ? 5 : listItems.length >= 1 ? 2 : 0",
"",
"    var geoMatches = (content.match(/\\b(local|nearby|community|neighborhood|residents|area|city|town)\\b/gi) || [])",
"    breakdown.localSeo = geoMatches.length >= 5 ? 10 : geoMatches.length >= 3 ? 7 : geoMatches.length >= 1 ? 3 : 0",
"",
"    var stats = (content.match(/\\b\\d+(\\.\\d+)?\\s*(%|percent|million|billion|thousand)/gi) || [])",
"    var citations = (content.match(/\\b(according to|research shows|studies show|data shows|survey|report)\\b/gi) || [])",
"    var totalStats = stats.length + citations.length",
"    breakdown.statistics = totalStats >= 5 ? 10 : totalStats >= 3 ? 7 : totalStats >= 1 ? 3 : 0",
"",
"    var strongCta = /\\b(schedule|book a|get your free|start today|claim|contact us today|get started today|free consultation)\\b/i.test(content)",
"    var weakCta = /\\b(contact|learn more|click|sign up|try|discover|reach out)\\b/i.test(content)",
"    breakdown.cta = strongCta ? 8 : weakCta ? 4 : 0",
"",
"    breakdown.paragraphs = paragraphs.length >= 10 ? 8 : paragraphs.length >= 7 ? 6 : paragraphs.length >= 4 ? 3 : 1",
"",
"    var firstSentence = sentences[0] || ''",
"    var firstWordCount = firstSentence.trim().split(/\\s+/).length",
"    if (firstWordCount <= 20 && firstWordCount >= 8 && /\\b(did you know|are you|imagine|every|most|the truth|stop|what if|in today|for many)\\b/i.test(firstSentence)) breakdown.openingHook = 5",
"    else if (firstWordCount <= 25) breakdown.openingHook = 2",
"    else breakdown.openingHook = 0",
"",
"    var titleWords = title.toLowerCase().split(/\\s+/).filter(function(w) { return w.length > 4 })",
"    var contentLower = content.toLowerCase()",
"    var matchingKw = titleWords.filter(function(w) { return (contentLower.match(new RegExp(w, 'g')) || []).length >= 3 })",
"    breakdown.keywords = matchingKw.length >= 3 ? 4 : matchingKw.length >= 1 ? 2 : 0",
"",
"  } else {",
"    breakdown.length = (wordCount >= 40 && wordCount <= 150) ? 20 : wordCount >= 20 ? 12 : 4",
"    breakdown.cta = /\\b(comment|share|follow|click|dm|tag|save|like|check out)\\b/i.test(content) ? 15 : 0",
"    breakdown.hook = sentences.length > 0 && sentences[0].split(/\\s+/).length <= 12 ? 15 : 7",
"    breakdown.local = /\\b(local|community|city|area|neighborhood)\\b/i.test(content) ? 10 : 0",
"    breakdown.stats = /\\b\\d+%/i.test(content) ? 10 : 0",
"    breakdown.question = /\\?/.test(content) ? 5 : 0",
"    breakdown.lineBreaks = (content.match(/\\n/g) || []).length >= 2 ? 10 : 0",
"  }",
"",
"  var total = Object.values(breakdown).reduce(function(a, b) { return a + b }, 0)",
"  return { score: Math.min(100, total), breakdown: breakdown }",
"}",
"",
"export function getScoreFromResult(result) {",
"  if (typeof result === 'number') return result",
"  return (result && result.score) || 0",
"}",
"",
"export function getScoreLabel(score) {",
"  if (score >= 90) return { label: 'Excellent', color: '#22c55e', bg: 'rgba(34,197,94,0.1)', border: '#22c55e' }",
"  if (score >= 75) return { label: 'Good', color: '#eab308', bg: 'rgba(234,179,8,0.1)', border: '#eab308' }",
"  if (score >= 55) return { label: 'Fair', color: '#f97316', bg: 'rgba(249,115,22,0.1)', border: '#f97316' }",
"  return { label: 'Needs Work', color: '#ef4444', bg: 'rgba(239,68,68,0.1)', border: '#ef4444' }",
"}",
"",
"export function ContentScoreBadge({ score, showLabel, size }) {",
"  showLabel = showLabel !== false",
"  size = size || 'md'",
"  var numScore = typeof score === 'object' ? score.score : score",
"  var meta = getScoreLabel(numScore)",
"  var isLg = size === 'lg'",
"  var dim = isLg ? 56 : 48",
"  var circ = 2 * Math.PI * 15",
"  var offset = circ * (1 - numScore / 100)",
"  return (",
"    <div style={{ display:'inline-flex', alignItems:'center', gap:'10px', background:meta.bg, border:'2px solid '+meta.border, borderRadius:'10px', padding:isLg?'12px 18px':'8px 14px', boxShadow:'0 2px 12px '+meta.color+'40' }}>",
"      <div style={{ position:'relative', width:dim+'px', height:dim+'px', flexShrink:0 }}>",
"        <svg viewBox='0 0 36 36' style={{ width:'100%', height:'100%', transform:'rotate(-90deg)' }}>",
"          <circle cx='18' cy='18' r='15' fill='none' stroke='#1a1a1a' strokeWidth='3' />",
"          <circle cx='18' cy='18' r='15' fill='none' stroke={meta.color} strokeWidth='3'",
"            strokeDasharray={circ} strokeDashoffset={offset} strokeLinecap='round' />",
"        </svg>",
"        <div style={{ position:'absolute', inset:0, display:'flex', alignItems:'center', justifyContent:'center', fontSize:isLg?'15px':'13px', fontWeight:900, color:meta.color, fontFamily:'DM Sans, sans-serif' }}>",
"          {numScore}",
"        </div>",
"      </div>",
"      {showLabel && (",
"        <div>",
"          <div style={{ fontSize:isLg?'15px':'14px', fontWeight:900, color:meta.color, fontFamily:'DM Sans, sans-serif' }}>{meta.label}</div>",
"          <div style={{ fontSize:isLg?'12px':'11px', color:'#888', fontFamily:'DM Sans, sans-serif', fontWeight:600 }}>Content Score</div>",
"        </div>",
"      )}",
"    </div>",
"  )",
"}",
];

fs.writeFileSync(path.join(base, 'components', 'ContentScore.tsx'), scoreLines.join('\n'), 'utf8');
console.log('SUCCESS: ContentScore.tsx written');

// Boost route
const boostLines = [
"// @ts-nocheck",
"import { NextResponse } from 'next/server'",
"import { createClient } from '@supabase/supabase-js'",
"import Anthropic from '@anthropic-ai/sdk'",
"",
"export async function POST(request) {",
"  const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY)",
"  const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })",
"  const { title, content, currentScore, breakdown, userId, businessId, postId } = await request.json()",
"  try {",
"    const { data: bp } = await supabase.from('business_profiles').select('business_name, industry, phone, website').eq('id', businessId).single()",
"    const businessName = bp?.business_name || 'this business'",
"    const city = bp?.phone || 'your local area'",
"    const industry = bp?.industry || 'business'",
"    const website = bp?.website || ''",
"    const fixes = []",
"    if (breakdown) {",
"      if ((breakdown.wordCount || 0) < 16) fixes.push('EXPAND to at least 1200 words with more detail and examples')",
"      if ((breakdown.headings || 0) < 8) fixes.push('ADD at least 5 H2 subheadings using ## format')",
"      if ((breakdown.lists || 0) < 5) fixes.push('ADD at least 2 bullet lists using - format with 4+ items each')",
"      if ((breakdown.statistics || 0) < 7) fixes.push('ADD at least 4 real statistics with percentages')",
"      if ((breakdown.localSeo || 0) < 7) fixes.push('MENTION the city ' + city + ' at least 5 times')",
"      if ((breakdown.cta || 0) < 8) fixes.push('ADD a strong CTA like Schedule your free consultation today')",
"      if ((breakdown.openingHook || 0) < 3) fixes.push('REWRITE opening sentence as a compelling hook under 20 words')",
"      if ((breakdown.keywords || 0) < 2) fixes.push('USE main title keywords at least 3 times each in the content')",
"    }",
"    const fixList = fixes.length > 0 ? fixes.join('\\n') : 'Improve overall quality depth and SEO'",
"    const parts = [",
"      'You are a world-class SEO content writer. Rewrite this blog post to score 90+ on SEO.',",
"      '',",
"      'SPECIFIC FIXES NEEDED:',",
"      fixList,",
"      '',",
"      'RULES - NEVER VIOLATE:',",
"      '- NEVER add phone numbers',",
"      '- NEVER add fake offers or dollar values',",
"      '- NEVER add fake testimonials or reviews',",
"      '- Only use real general industry statistics',",
"      '- Keep the same topic and business focus',",
"      '- Business name: ' + businessName,",
"      '- City: ' + city,",
"      '- Industry: ' + industry,",
"      '- Website: ' + website,",
"      '',",
"      'TITLE: ' + title,",
"      '',",
"      'CONTENT:',",
"      content,",
"      '',",
"      'Return ONLY valid JSON no markdown: {\"title\": \"improved title\", \"content\": \"full improved content\"}'",
"    ]",
"    const prompt = parts.join('\\n')",
"    const message = await anthropic.messages.create({",
"      model: 'claude-opus-4-5-20251101',",
"      max_tokens: 4000,",
"      messages: [{ role: 'user', content: prompt }]",
"    })",
"    const responseText = message.content[0].text.trim()",
"    const clean = responseText.replace(/```json|```/g, '').trim()",
"    const parsed = JSON.parse(clean)",
"    if (postId) {",
"      await supabase.from('content_calendar').update({ title: parsed.title, content: parsed.content }).eq('id', postId)",
"    }",
"    return NextResponse.json({ title: parsed.title, content: parsed.content })",
"  } catch (e) {",
"    console.error('Boost error:', e)",
"    return NextResponse.json({ error: e.message }, { status: 500 })",
"  }",
"}",
];

const boostDir = path.join(base, 'app', 'api', 'content', 'boost');
fs.mkdirSync(boostDir, { recursive: true });
fs.writeFileSync(path.join(boostDir, 'route.ts'), boostLines.join('\n'), 'utf8');
console.log('SUCCESS: boost/route.ts written');

// Blog page
const blogLines = [
"// @ts-nocheck",
"'use client'",
"import { useState, useEffect } from 'react'",
"import { supabase } from '@/lib/supabase'",
"import { calculateContentScore, getScoreFromResult, ContentScoreBadge } from '@/components/ContentScore'",
"",
"export default function BlogPage() {",
"  const [userId, setUserId] = useState('')",
"  const [businessId, setBusinessId] = useState('')",
"  const [topic, setTopic] = useState('')",
"  const [generating, setGenerating] = useState(false)",
"  const [boosting, setBoosting] = useState(false)",
"  const [publishing, setPublishing] = useState(false)",
"  const [post, setPost] = useState(null)",
"  const [message, setMessage] = useState('')",
"  const [wpMessage, setWpMessage] = useState('')",
"  const [businessName, setBusinessName] = useState('')",
"  const [charCount, setCharCount] = useState(0)",
"  const [userStatus, setUserStatus] = useState('free')",
"  const [blogsUsed, setBlogsUsed] = useState(0)",
"  const [boostMessage, setBoostMessage] = useState('')",
"  const [boosted, setBoosted] = useState(false)",
"  const [scoreResult, setScoreResult] = useState(null)",
"",
"  useEffect(() => {",
"    const load = async () => {",
"      const { data: { user } } = await supabase.auth.getUser()",
"      if (!user) return",
"      setUserId(user.id)",
"      const { data: bp } = await supabase.from('business_profiles').select('id, business_name').eq('user_id', user.id).single()",
"      if (bp) { setBusinessId(bp.id); setBusinessName(bp.business_name || '') }",
"      const { data: userData } = await supabase.from('users').select('status').eq('id', user.id).single()",
"      if (userData?.status) setUserStatus(userData.status)",
"      try {",
"        const now = new Date()",
"        const firstOfMonth = new Date(now.getFullYear(), now.getMonth(), 1).toISOString()",
"        const { count } = await supabase.from('blog_generations').select('*', { count: 'exact', head: true }).eq('user_id', user.id).gte('created_at', firstOfMonth)",
"        setBlogsUsed(count || 0)",
"      } catch (e) { setBlogsUsed(0) }",
"    }",
"    load()",
"  }, [])",
"",
"  const isPaid = userStatus && userStatus !== 'free'",
"  const freeLimit = 3",
"  const freeExceeded = !isPaid && blogsUsed >= freeLimit",
"  const currentScore = scoreResult ? getScoreFromResult(scoreResult) : 0",
"",
"  function recalcScore(p) {",
"    if (!p) return",
"    setScoreResult(calculateContentScore(p.content, p.title, 'blog'))",
"  }",
"",
"  const generate = async () => {",
"    if (!topic.trim()) return",
"    if (freeExceeded) { setMessage('You\u2019ve used all 3 free blogs this month.'); return }",
"    setGenerating(true); setMessage(''); setPost(null); setWpMessage(''); setBoostMessage(''); setBoosted(false); setScoreResult(null)",
"    try {",
"      const res = await fetch('/api/content/blog', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ userId, businessId, topic }) })",
"      const data = await res.json()",
"      if (data.error) { setMessage(data.error) }",
"      else { setPost(data); recalcScore(data); if (!isPaid) setBlogsUsed(prev => prev + 1) }",
"    } catch (e) { setMessage('Something went wrong. Try again.') }",
"    setGenerating(false)",
"  }",
"",
"  const boostScore = async () => {",
"    if (!post || !isPaid) return",
"    setBoosting(true); setBoostMessage('')",
"    try {",
"      const res = await fetch('/api/content/boost', {",
"        method: 'POST',",
"        headers: { 'Content-Type': 'application/json' },",
"        body: JSON.stringify({ title: post.title, content: post.content, currentScore, breakdown: scoreResult?.breakdown || {}, userId, businessId, postId: post.id })",
"      })",
"      const data = await res.json()",
"      if (data.error) { setBoostMessage('Boost failed: ' + data.error) }",
"      else {",
"        const updated = { ...post, content: data.content, title: data.title || post.title }",
"        setPost(updated)",
"        recalcScore(updated)",
"        setBoostMessage('\u2b06\ufe0f Content enhanced! Check your new score above.')",
"        setBoosted(true)",
"      }",
"    } catch (e) { setBoostMessage('Something went wrong. Try again.') }",
"    setBoosting(false)",
"  }",
"",
"  const publishToWordPress = async () => {",
"    if (!post) return",
"    setPublishing(true); setWpMessage('')",
"    try {",
"      const res = await fetch('/api/content/wordpress', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ postId: post.id, userId }) })",
"      const data = await res.json()",
"      if (data.error) { setWpMessage('Error: ' + data.error) }",
"      else { setWpMessage('Published! View post: ' + data.wpPostUrl) }",
"    } catch (e) { setWpMessage('Something went wrong. Try again.') }",
"    setPublishing(false)",
"  }",
"",
"  const inp = { width:'100%', background:'#0a0a0a', border:'1px solid #2a2a2a', borderRadius:'10px', padding:'14px 16px', fontSize:'15px', color:'#fff', resize:'vertical', boxSizing:'border-box', fontFamily:'DM Sans, sans-serif', outline:'none', lineHeight:1.6 }",
"",
"  return (",
"    <div style={{ minHeight:'100vh', background:'#0a0a0a' }}>",
"      <div style={{ background:'linear-gradient(135deg,#111 0%,#1a0e00 100%)', borderBottom:'1px solid #1e1e1e', padding:'32px 40px' }}>",
"        <div style={{ maxWidth:'860px', margin:'0 auto' }}>",
"          <div style={{ display:'flex', alignItems:'center', gap:'12px', marginBottom:'8px' }}>",
"            <div style={{ width:'36px', height:'36px', background:'linear-gradient(135deg,#E8610A,#ff8c42)', borderRadius:'8px', display:'flex', alignItems:'center', justifyContent:'center', fontSize:'18px' }}>\u270f\ufe0f</div>",
"            <div>",
"              <h1 style={{ fontFamily:'Playfair Display, serif', fontSize:'26px', fontWeight:900, color:'#fff', margin:0 }}>Blog Generator</h1>",
"              <p style={{ color:'#666', fontSize:'13px', margin:0, fontFamily:'DM Sans, sans-serif' }}>Powered by your Business Brain \u2014 AI that knows your business</p>",
"            </div>",
"          </div>",
"          <div style={{ display:'flex', alignItems:'center', gap:12, marginTop:12, flexWrap:'wrap' }}>",
"            {businessName && <div style={{ display:'inline-flex', alignItems:'center', gap:'6px', background:'rgba(232,97,10,0.1)', border:'1px solid rgba(232,97,10,0.3)', borderRadius:'20px', padding:'4px 14px' }}><div style={{ width:'6px', height:'6px', borderRadius:'50%', background:'#E8610A' }} /><span style={{ fontSize:'12px', color:'#E8610A', fontFamily:'DM Sans, sans-serif', fontWeight:600 }}>{businessName}</span></div>}",
"            {!isPaid && <div style={{ display:'inline-flex', alignItems:'center', gap:8, background:'rgba(232,97,10,0.08)', border:'1px solid rgba(232,97,10,0.2)', borderRadius:'20px', padding:'4px 14px' }}><span style={{ fontSize:'12px', color:freeExceeded?'#ef4444':'#E8610A', fontFamily:'DM Sans, sans-serif', fontWeight:600 }}>{blogsUsed}/{freeLimit} free blogs used</span>{freeExceeded && <a href='/pricing' style={{ background:'#E8610A', color:'#fff', padding:'2px 10px', borderRadius:4, fontSize:11, fontWeight:700, textDecoration:'none' }}>Upgrade</a>}</div>}",
"          </div>",
"        </div>",
"      </div>",
"      <div style={{ maxWidth:'860px', margin:'0 auto', padding:'32px 40px' }}>",
"        <div style={{ display:'grid', gridTemplateColumns:'repeat(3,1fr)', gap:'12px', marginBottom:'28px' }}>",
"          {[{label:'SEO Optimized',value:'100%',icon:'\ud83d\udcc8'},{label:'Avg Word Count',value:'900+',icon:'\ud83d\udcdd'},{label:'AI Platforms',value:'6+',icon:'\ud83e\udd16'}].map(stat => (",
"            <div key={stat.label} style={{ background:'#111', border:'1px solid #1e1e1e', borderRadius:'10px', padding:'16px 20px', display:'flex', alignItems:'center', gap:'12px' }}>",
"              <span style={{ fontSize:'20px' }}>{stat.icon}</span>",
"              <div><div style={{ fontFamily:'Playfair Display, serif', fontSize:'20px', fontWeight:700, color:'#E8610A', lineHeight:1 }}>{stat.value}</div><div style={{ fontSize:'11px', color:'#555', fontFamily:'DM Sans, sans-serif', marginTop:'2px' }}>{stat.label}</div></div>",
"            </div>",
"          ))}",
"        </div>",
"        <div style={{ background:'#111', border:'1px solid #1e1e1e', borderRadius:'14px', padding:'28px', marginBottom:'24px' }}>",
"          <label style={{ display:'block', fontSize:'13px', fontWeight:700, color:'#aaa', marginBottom:'10px', fontFamily:'DM Sans, sans-serif', letterSpacing:'0.08em', textTransform:'uppercase' }}>Blog Topic</label>",
"          <div style={{ position:'relative' }}>",
"            <textarea rows={3} placeholder='e.g. 5 reasons local businesses need AI marketing in 2026...' value={topic} onChange={e => { setTopic(e.target.value); setCharCount(e.target.value.length) }} style={inp} onFocus={e => e.target.style.borderColor='#E8610A'} onBlur={e => e.target.style.borderColor='#2a2a2a'} />",
"            <div style={{ position:'absolute', bottom:'10px', right:'14px', fontSize:'11px', color:'#444' }}>{charCount} chars</div>",
"          </div>",
"          <div style={{ display:'flex', alignItems:'center', justifyContent:'space-between', marginTop:'16px', flexWrap:'wrap', gap:'12px' }}>",
"            <div style={{ display:'flex', gap:'8px', flexWrap:'wrap' }}>",
"              {['AI Marketing Tips','Local SEO Guide','Why Choose Us','Customer Success'].map(s => (",
"                <button key={s} onClick={() => { setTopic(s); setCharCount(s.length) }} style={{ background:'#1a1a1a', border:'1px solid #2a2a2a', borderRadius:'20px', padding:'5px 12px', fontSize:'11px', color:'#888', cursor:'pointer', fontFamily:'DM Sans, sans-serif' }} onMouseEnter={e => { e.target.style.borderColor='#E8610A'; e.target.style.color='#E8610A' }} onMouseLeave={e => { e.target.style.borderColor='#2a2a2a'; e.target.style.color='#888' }}>{s}</button>",
"              ))}",
"            </div>",
"            <button onClick={generate} disabled={generating||!topic.trim()||freeExceeded} style={{ background:(generating||freeExceeded)?'#2a2a2a':'linear-gradient(135deg,#E8610A,#ff8c42)', color:(generating||freeExceeded)?'#666':'#fff', padding:'12px 28px', borderRadius:'8px', fontSize:'14px', fontWeight:700, border:'none', cursor:(generating||freeExceeded)?'not-allowed':'pointer', fontFamily:'DM Sans, sans-serif', display:'flex', alignItems:'center', gap:'8px', boxShadow:(generating||freeExceeded)?'none':'0 4px 20px rgba(232,97,10,0.35)' }}>",
"              {freeExceeded ? '\ud83d\udd12 Limit Reached' : generating ? '\u23f3 Generating...' : '\u26a1 Generate Blog Post'}",
"            </button>",
"          </div>",
"          {freeExceeded && <div style={{ marginTop:14, background:'rgba(232,97,10,0.08)', border:'1px solid rgba(232,97,10,0.2)', borderRadius:8, padding:'12px 16px', display:'flex', alignItems:'center', justifyContent:'space-between', flexWrap:'wrap', gap:8 }}><span style={{ color:'#E8610A', fontSize:13, fontFamily:'DM Sans, sans-serif' }}>You\u2019ve used all 3 free blogs this month.</span><a href='/pricing' style={{ background:'linear-gradient(135deg,#E8610A,#C84E06)', color:'#fff', padding:'8px 20px', borderRadius:6, fontSize:13, fontWeight:700, textDecoration:'none' }}>Upgrade \u2014 $47/mo</a></div>}",
"          {message && <div style={{ marginTop:'14px', background:'rgba(239,68,68,0.08)', border:'1px solid rgba(239,68,68,0.2)', borderRadius:'8px', padding:'10px 14px', fontSize:'13px', color:'#f87171', fontFamily:'DM Sans, sans-serif' }}>{message}</div>}",
"        </div>",
"        {generating && <div style={{ background:'#111', border:'1px solid #1e1e1e', borderRadius:'14px', padding:'40px', textAlign:'center', marginBottom:'24px' }}><div style={{ fontSize:'36px', marginBottom:'16px' }}>\u270f\ufe0f</div><p style={{ fontFamily:'Playfair Display, serif', fontSize:'20px', color:'#fff', marginBottom:'8px' }}>Writing your blog post...</p><p style={{ fontFamily:'DM Sans, sans-serif', fontSize:'13px', color:'#555' }}>Your Business Brain is crafting SEO-optimized content for your business.</p></div>}",
"        {boosting && <div style={{ background:'#111', border:'1px solid rgba(34,197,94,0.3)', borderRadius:'14px', padding:'28px', textAlign:'center', marginBottom:'24px' }}><div style={{ fontSize:'32px', marginBottom:'12px' }}>\u26a1</div><p style={{ fontFamily:'Playfair Display, serif', fontSize:'18px', color:'#22c55e', marginBottom:'6px' }}>Boosting your content score...</p><p style={{ fontFamily:'DM Sans, sans-serif', fontSize:'13px', color:'#555' }}>AI is fixing specific weak points \u2014 adding structure, stats, local SEO and more.</p></div>}",
"        {post && !boosting && (",
"          <div style={{ background:'#111', border:'1px solid #1e1e1e', borderRadius:'14px', overflow:'hidden', marginBottom:'24px' }}>",
"            <div style={{ background:'linear-gradient(135deg,#1a0e00,#111)', borderBottom:'1px solid #1e1e1e', padding:'20px 28px', display:'flex', alignItems:'center', justifyContent:'space-between', flexWrap:'wrap', gap:'12px' }}>",
"              <div style={{ display:'flex', alignItems:'center', gap:'12px', flexWrap:'wrap' }}>",
"                <div style={{ width:'8px', height:'8px', borderRadius:'50%', background:'#22c55e' }} />",
"                <span style={{ fontFamily:'DM Sans, sans-serif', fontSize:'13px', color:'#22c55e', fontWeight:600 }}>Blog post ready</span>",
"                {scoreResult && <ContentScoreBadge score={currentScore} size='md' />}",
"              </div>",
"              <div style={{ display:'flex', gap:'10px', flexWrap:'wrap' }}>",
"                {isPaid && currentScore < 90 && !boosted && <button onClick={boostScore} style={{ background:'linear-gradient(135deg,#dc2626,#b91c1c)', color:'#fff', padding:'9px 18px', borderRadius:'7px', fontSize:'13px', fontWeight:700, border:'none', cursor:'pointer', fontFamily:'DM Sans, sans-serif', boxShadow:'0 4px 16px rgba(220,38,38,0.5)' }}>\ud83d\udd25 Boost Score</button>}",
"                {!isPaid && currentScore < 90 && !boosted && <a href='/pricing' style={{ background:'#1a1a1a', color:'#ef4444', border:'1px solid rgba(239,68,68,0.3)', padding:'9px 18px', borderRadius:'7px', fontSize:'13px', fontWeight:700, textDecoration:'none', fontFamily:'DM Sans, sans-serif' }}>\ud83d\udd25 Boost Score \u2014 Upgrade</a>}",
"                {boosted && <div style={{ display:'flex', alignItems:'center', gap:'6px', background:'rgba(34,197,94,0.1)', border:'1px solid rgba(34,197,94,0.3)', borderRadius:'7px', padding:'9px 14px', fontSize:'13px', color:'#22c55e', fontWeight:700 }}>\u2705 Score Boosted</div>}",
"                {isPaid && <button onClick={publishToWordPress} disabled={publishing} style={{ background:publishing?'#1a1a1a':'linear-gradient(135deg,#16a34a,#15803d)', color:publishing?'#555':'#fff', padding:'9px 20px', borderRadius:'7px', fontSize:'13px', fontWeight:700, border:'none', cursor:publishing?'not-allowed':'pointer', fontFamily:'DM Sans, sans-serif' }}>{publishing ? '\u23f3 Publishing...' : '\ud83c\udf10 Publish to WordPress'}</button>}",
"              </div>",
"            </div>",
"            {boostMessage && <div style={{ margin:'16px 28px 0', background:'rgba(34,197,94,0.08)', border:'1px solid rgba(34,197,94,0.3)', borderRadius:'8px', padding:'10px 14px', fontSize:'13px', color:'#4ade80', fontFamily:'DM Sans, sans-serif', fontWeight:600 }}>{boostMessage}</div>}",
"            {scoreResult && scoreResult.breakdown && (",
"              <div style={{ margin:'16px 28px 0', background:'#0d0d0d', border:'1px solid #1a1a1a', borderRadius:'10px', padding:'16px' }}>",
"                <div style={{ fontSize:'11px', color:'#555', fontWeight:700, letterSpacing:'0.1em', textTransform:'uppercase', marginBottom:'10px', fontFamily:'DM Sans, sans-serif' }}>Score Breakdown</div>",
"                <div style={{ display:'grid', gridTemplateColumns:'repeat(5,1fr)', gap:'8px' }}>",
"                  {Object.entries(scoreResult.breakdown).map(function(entry) {",
"                    var key = entry[0]; var val = entry[1]",
"                    var labels = { wordCount:'Word Count', titleQuality:'Title', headings:'Headings', lists:'Lists', localSeo:'Local SEO', statistics:'Stats', cta:'CTA', paragraphs:'Paragraphs', openingHook:'Hook', keywords:'Keywords' }",
"                    var maxVals = { wordCount:20, titleQuality:15, headings:12, lists:8, localSeo:10, statistics:10, cta:8, paragraphs:8, openingHook:5, keywords:4 }",
"                    var pct = Math.round((val / (maxVals[key] || 10)) * 100)",
"                    var c = pct >= 80 ? '#22c55e' : pct >= 50 ? '#eab308' : '#ef4444'",
"                    return (",
"                      <div key={key} style={{ textAlign:'center' }}>",
"                        <div style={{ fontSize:'14px', fontWeight:900, color:c, fontFamily:'DM Sans, sans-serif' }}>{val}</div>",
"                        <div style={{ fontSize:'9px', color:'#444', fontFamily:'DM Sans, sans-serif', marginTop:'2px' }}>{labels[key] || key}</div>",
"                        <div style={{ height:'3px', background:'#1a1a1a', borderRadius:'2px', marginTop:'4px' }}><div style={{ height:'100%', width:pct+'%', background:c, borderRadius:'2px' }} /></div>",
"                      </div>",
"                    )",
"                  })}",
"                </div>",
"              </div>",
"            )}",
"            <div style={{ padding:'24px 28px 0' }}>",
"              <h2 style={{ fontFamily:'Playfair Display, serif', fontSize:'22px', fontWeight:900, color:'#fff', margin:'0 0 16px', lineHeight:1.3 }}>{post.title}</h2>",
"              <div style={{ height:'1px', background:'linear-gradient(90deg,#E8610A,transparent)', marginBottom:'20px' }} />",
"            </div>",
"            <div style={{ padding:'0 28px 28px', position:'relative' }}>",
"              <div style={{ background:'#0a0a0a', border:'1px solid #1e1e1e', borderRadius:'10px', padding:'20px', maxHeight:isPaid?'400px':'200px', overflowY:isPaid?'auto':'hidden', filter:isPaid?'none':'blur(4px)', pointerEvents:isPaid?'auto':'none', userSelect:isPaid?'auto':'none' }}>",
"                <p style={{ fontFamily:'DM Sans, sans-serif', fontSize:'14px', color:'#ccc', lineHeight:1.85, whiteSpace:'pre-wrap', margin:0 }}>{post.content}</p>",
"              </div>",
"              {!isPaid && (",
"                <div style={{ position:'absolute', bottom:28, left:28, right:28, background:'linear-gradient(transparent,#111 60%)', paddingTop:60, paddingBottom:28, display:'flex', flexDirection:'column', alignItems:'center', gap:12, borderRadius:'0 0 10px 10px' }}>",
"                  <div style={{ fontSize:36 }}>\ud83d\udd12</div>",
"                  <p style={{ fontFamily:'Playfair Display, serif', fontSize:20, fontWeight:700, color:'#fff', margin:0, textAlign:'center' }}>Your blog post is ready</p>",
"                  <p style={{ fontFamily:'DM Sans, sans-serif', fontSize:13, color:'#888', margin:0, textAlign:'center' }}>Upgrade to copy, publish to WordPress, and get unlimited blogs</p>",
"                  <a href='/pricing' style={{ background:'linear-gradient(135deg,#E8610A,#C84E06)', color:'#fff', padding:'12px 32px', borderRadius:8, fontWeight:700, fontSize:14, textDecoration:'none', boxShadow:'0 4px 20px rgba(232,97,10,0.35)', fontFamily:'DM Sans, sans-serif' }}>Upgrade to Starter \u2014 $47/month</a>",
"                  <p style={{ color:'#555', fontSize:11, margin:0, fontFamily:'DM Sans, sans-serif' }}>Unlimited blogs \u2022 Social content \u2022 Manual publish</p>",
"                </div>",
"              )}",
"            </div>",
"            {wpMessage && <div style={{ margin:'0 28px 24px', background:wpMessage.startsWith('Error')?'rgba(239,68,68,0.08)':'rgba(34,197,94,0.08)', border:'1px solid '+(wpMessage.startsWith('Error')?'rgba(239,68,68,0.2)':'rgba(34,197,94,0.2)'), borderRadius:'8px', padding:'12px 16px', fontSize:'13px', color:wpMessage.startsWith('Error')?'#f87171':'#4ade80', fontFamily:'DM Sans, sans-serif' }}>{wpMessage}</div>}",
"          </div>",
"        )}",
"        {!post && !generating && (",
"          <div style={{ background:'#111', border:'1px solid #1e1e1e', borderRadius:'14px', padding:'24px 28px' }}>",
"            <p style={{ fontFamily:'DM Sans, sans-serif', fontSize:'12px', fontWeight:700, color:'#444', letterSpacing:'0.1em', textTransform:'uppercase', marginBottom:'16px' }}>Pro Tips</p>",
"            <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:'12px' }}>",
"              {[{icon:'\ud83c\udfaf',tip:'Be specific with your topic for better SEO targeting'},{icon:'\ud83d\udcc8',tip:'Include your city or region for local SEO boost'},{icon:'\ud83e\udd16',tip:'Your Brain auto-injects your business context'},{icon:'\ud83c\udf10',tip:'Publish directly to WordPress with one click'}].map(function(item) {",
"                return (",
"                  <div key={item.tip} style={{ display:'flex', gap:'10px', alignItems:'flex-start' }}>",
"                    <span style={{ fontSize:'16px', flexShrink:0 }}>{item.icon}</span>",
"                    <p style={{ fontFamily:'DM Sans, sans-serif', fontSize:'13px', color:'#555', margin:0, lineHeight:1.6 }}>{item.tip}</p>",
"                  </div>",
"                )",
"              })}",
"            </div>",
"          </div>",
"        )}",
"      </div>",
"    </div>",
"  )",
"}",
];

fs.writeFileSync(path.join(base, 'app', 'dashboard', 'content', 'blog', 'page.tsx'), blogLines.join('\n'), 'utf8');
console.log('SUCCESS: Blog page written');
console.log('ALL DONE - run: npx next build');