const fs = require('fs');
const lines = [
"'use client'",
"",
"import { useState, useEffect } from 'react'",
"import { supabase } from '@/lib/supabase'",
"",
"export default function BusinessProfilePage() {",
"  const [loading, setLoading] = useState(true)",
"  const [saving, setSaving] = useState(false)",
"  const [message, setMessage] = useState('')",
"  const [form, setForm] = useState({ business_name: '', industry: '', website: '', phone: '', email: '', city: '', state: '', zip: '', description: '' })",
"  useEffect(() => { loadProfile() }, [])",
"  async function loadProfile() {",
"    setLoading(true)",
"    const { data: { user } } = await supabase.auth.getUser()",
"    if (!user) return",
"    const { data } = await supabase.from('business_profiles').select('*').eq('user_id', user.id).single()",
"    if (data) { setForm({ business_name: data.business_name||'', industry: data.industry||'', website: data.website||'', phone: data.phone||'', email: data.email||'', city: data.city||'', state: data.state||'', zip: data.zip||'', description: data.description||'' }) }",
"    setLoading(false)",
"  }",
"  async function handleSave() {",
"    setSaving(true); setMessage('')",
"    const { data: { user } } = await supabase.auth.getUser()",
"    if (!user) return",
"    const { error } = await supabase.from('business_profiles').upsert({ user_id: user.id, ...form, updated_at: new Date().toISOString() }, { onConflict: 'user_id' })",
"    if (error) { setMessage('Error: ' + error.message) } else { setMessage('Saved!') }",
"    setSaving(false)",
"  }",
"  if (loading) return <div className=\"flex items-center justify-center h-64\"><div className=\"text-gray-400\">Loading...</div></div>",
"  return (",
"    <div className=\"max-w-3xl mx-auto px-4 py-8\">",
"      <h1 className=\"text-2xl font-bold text-white mb-1\">Business Profile</h1>",
"      <p className=\"text-gray-400 mb-8\">This info powers your marketing across all channels.</p>",
"      <div className=\"bg-gray-900 border border-gray-800 rounded-xl p-6 mb-6\">",
"        <h2 className=\"text-white font-semibold mb-4\">Business Information</h2>",
"        <div className=\"grid grid-cols-1 md:grid-cols-2 gap-4\">",
"          <div className=\"md:col-span-2\"><label className=\"text-gray-400 text-sm mb-1 block\">Business Name</label><input type=\"text\" value={form.business_name} onChange={e => setForm({...form, business_name: e.target.value})} className=\"w-full bg-gray-800 border border-gray-700 rounded-lg px-4 py-2 text-white\" placeholder=\"Your Business Name\" /></div>",
"          <div><label className=\"text-gray-400 text-sm mb-1 block\">Website</label><input type=\"text\" value={form.website} onChange={e => setForm({...form, website: e.target.value})} className=\"w-full bg-gray-800 border border-gray-700 rounded-lg px-4 py-2 text-white\" placeholder=\"https://yourbusiness.com\" /></div>",
"          <div><label className=\"text-gray-400 text-sm mb-1 block\">Phone</label><input type=\"text\" value={form.phone} onChange={e => setForm({...form, phone: e.target.value})} className=\"w-full bg-gray-800 border border-gray-700 rounded-lg px-4 py-2 text-white\" placeholder=\"+1 (555) 000-0000\" /></div>",
"          <div><label className=\"text-gray-400 text-sm mb-1 block\">Email</label><input type=\"email\" value={form.email} onChange={e => setForm({...form, email: e.target.value})} className=\"w-full bg-gray-800 border border-gray-700 rounded-lg px-4 py-2 text-white\" placeholder=\"hello@yourbusiness.com\" /></div>",
"          <div><label className=\"text-gray-400 text-sm mb-1 block\">City</label><input type=\"text\" value={form.city} onChange={e => setForm({...form, city: e.target.value})} className=\"w-full bg-gray-800 border border-gray-700 rounded-lg px-4 py-2 text-white\" placeholder=\"Miami\" /></div>",
"          <div><label className=\"text-gray-400 text-sm mb-1 block\">State</label><input type=\"text\" value={form.state} onChange={e => setForm({...form, state: e.target.value})} className=\"w-full bg-gray-800 border border-gray-700 rounded-lg px-4 py-2 text-white\" placeholder=\"FL\" /></div>",
"          <div className=\"md:col-span-2\"><label className=\"text-gray-400 text-sm mb-1 block\">Description</label><textarea value={form.description} onChange={e => setForm({...form, description: e.target.value})} rows={3} className=\"w-full bg-gray-800 border border-gray-700 rounded-lg px-4 py-2 text-white resize-none\" placeholder=\"What does your business do?\" /></div>",
"        </div>",
"      </div>",
"      {message && <p className=\"mb-4 text-sm text-green-400\">{message}</p>}",
"      <button onClick={handleSave} disabled={saving} className=\"w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-3 rounded-xl\">{saving ? 'Saving...' : 'Save Business Profile'}</button>",
"    </div>",
"  )",
"}"
];
fs.writeFileSync('src/app/dashboard/business/page.tsx', lines.join('\n'));
console.log('done');
