// @ts-nocheck
'use client'
import Link from 'next/link'

export default function GlossaryPage() {
  return (
    <main suppressHydrationWarning style={{ minHeight: '100vh', background: '#111111', color: '#fff', fontFamily: 'DM Sans, sans-serif' }}>
      <section style={{ padding: '112px 24px 64px', textAlign: 'center', background: 'linear-gradient(135deg, #111111 0%, #1a1a1a 50%, #111111 100%)' }}>
        <p style={{ color: '#E8610A', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.15em', fontSize: '13px', margin: '0 0 16px 0' }}>Reference Guide</p>
        <h1 style={{ fontSize: 'clamp(32px, 6vw, 56px)', fontWeight: 700, color: '#fff', margin: '0 0 24px 0', lineHeight: 1.15 }}>AI &amp; SEO Marketing <span style={{ color: '#E8610A' }}>Glossary</span></h1>
        <p style={{ color: '#d1d5db', fontSize: '18px', maxWidth: '600px', margin: '0 auto 40px', lineHeight: 1.7 }}>Every term you need to understand AI marketing, local SEO, and generative engine optimization -- explained in plain English.</p>
      </section>
      <section style={{ maxWidth: '800px', margin: '0 auto', padding: '64px 24px 96px' }}>
        <div id='A' style={{ marginBottom: '56px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '16px', marginBottom: '24px' }}><span style={{ fontSize: '48px', fontWeight: 700, color: '#E8610A' }}>A</span><div style={{ flex: 1, height: '1px', background: '#E8610A', opacity: 0.3 }}></div></div>
          <div style={{ border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', padding: '24px', marginBottom: '16px' }}><h2 style={{ color: '#fff', fontSize: '17px', fontWeight: 700, margin: '0 0 8px 0' }}>AI Engine Optimization (AEO)</h2><p style={{ color: '#d1d5db', lineHeight: 1.7, margin: 0 }}>The practice of structuring your content so AI-powered answer engines like ChatGPT, Perplexity, and Google AI Overviews surface your business as a cited source. AEO is the evolution of traditional SEO.</p></div>
          <div style={{ border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', padding: '24px', marginBottom: '16px' }}><h2 style={{ color: '#fff', fontSize: '17px', fontWeight: 700, margin: '0 0 8px 0' }}>AI Marketing Automation</h2><p style={{ color: '#d1d5db', lineHeight: 1.7, margin: 0 }}>The use of artificial intelligence to plan, create, schedule, and optimize marketing content without constant manual input. Traffikora uses AI marketing automation to run your social, blog, and local SEO simultaneously.</p></div>
          <div style={{ border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', padding: '24px', marginBottom: '16px' }}><h2 style={{ color: '#fff', fontSize: '17px', fontWeight: 700, margin: '0 0 8px 0' }}>Algorithm</h2><p style={{ color: '#d1d5db', lineHeight: 1.7, margin: 0 }}>A set of rules used by search engines and social platforms to decide which content to show and in what order. Google, TikTok, and Instagram each use their own algorithms.</p></div>
          <div style={{ border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', padding: '24px', marginBottom: '16px' }}><h2 style={{ color: '#fff', fontSize: '17px', fontWeight: 700, margin: '0 0 8px 0' }}>Answer Engine</h2><p style={{ color: '#d1d5db', lineHeight: 1.7, margin: 0 }}>A search tool that returns a direct answer rather than a list of links. Examples include ChatGPT, Perplexity, and Google AI Overviews. Ranking in answer engines requires AEO strategy.</p></div>
        </div>
        <div id='B' style={{ marginBottom: '56px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '16px', marginBottom: '24px' }}><span style={{ fontSize: '48px', fontWeight: 700, color: '#E8610A' }}>B</span><div style={{ flex: 1, height: '1px', background: '#E8610A', opacity: 0.3 }}></div></div>
          <div style={{ border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', padding: '24px', marginBottom: '16px' }}><h2 style={{ color: '#fff', fontSize: '17px', fontWeight: 700, margin: '0 0 8px 0' }}>Backlink</h2><p style={{ color: '#d1d5db', lineHeight: 1.7, margin: 0 }}>A link from another website pointing to your site. High-quality backlinks from authoritative sites signal trust to search engines and improve your domain authority.</p></div>
          <div style={{ border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', padding: '24px', marginBottom: '16px' }}><h2 style={{ color: '#fff', fontSize: '17px', fontWeight: 700, margin: '0 0 8px 0' }}>Blog Automation</h2><p style={{ color: '#d1d5db', lineHeight: 1.7, margin: 0 }}>The process of using AI to automatically generate, optimize, and publish SEO blog posts on a recurring schedule. Traffikora blog automation publishes keyword-targeted articles without requiring you to write a single word.</p></div>
          <div style={{ border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', padding: '24px', marginBottom: '16px' }}><h2 style={{ color: '#fff', fontSize: '17px', fontWeight: 700, margin: '0 0 8px 0' }}>Brand Voice</h2><p style={{ color: '#d1d5db', lineHeight: 1.7, margin: 0 }}>The consistent personality, tone, and style a business uses across all its marketing content. A strong brand voice builds recognition and trust with customers.</p></div>
        </div>
        <div id='C' style={{ marginBottom: '56px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '16px', marginBottom: '24px' }}><span style={{ fontSize: '48px', fontWeight: 700, color: '#E8610A' }}>C</span><div style={{ flex: 1, height: '1px', background: '#E8610A', opacity: 0.3 }}></div></div>
          <div style={{ border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', padding: '24px', marginBottom: '16px' }}><h2 style={{ color: '#fff', fontSize: '17px', fontWeight: 700, margin: '0 0 8px 0' }}>Citations</h2><p style={{ color: '#d1d5db', lineHeight: 1.7, margin: 0 }}>Online mentions of your business name, address, and phone number across directories and websites. Consistent citations are a key local SEO ranking factor.</p></div>
          <div style={{ border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', padding: '24px', marginBottom: '16px' }}><h2 style={{ color: '#fff', fontSize: '17px', fontWeight: 700, margin: '0 0 8px 0' }}>Conversion Rate</h2><p style={{ color: '#d1d5db', lineHeight: 1.7, margin: 0 }}>The percentage of visitors who take a desired action such as booking an appointment or submitting a form. Improving conversion rate increases revenue without increasing ad spend.</p></div>
          <div style={{ border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', padding: '24px', marginBottom: '16px' }}><h2 style={{ color: '#fff', fontSize: '17px', fontWeight: 700, margin: '0 0 8px 0' }}>Core Web Vitals</h2><p style={{ color: '#d1d5db', lineHeight: 1.7, margin: 0 }}>Performance metrics defined by Google measuring page loading speed, interactivity, and visual stability. Passing Core Web Vitals is required for top search rankings.</p></div>
        </div>
        <div id='G' style={{ marginBottom: '56px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '16px', marginBottom: '24px' }}><span style={{ fontSize: '48px', fontWeight: 700, color: '#E8610A' }}>G</span><div style={{ flex: 1, height: '1px', background: '#E8610A', opacity: 0.3 }}></div></div>
          <div style={{ border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', padding: '24px', marginBottom: '16px' }}><h2 style={{ color: '#fff', fontSize: '17px', fontWeight: 700, margin: '0 0 8px 0' }}>Generative Engine Optimization (GEO)</h2><p style={{ color: '#d1d5db', lineHeight: 1.7, margin: 0 }}>A strategy for making your content readable and citable by AI-powered generative search engines. GEO focuses on structured answers and schema markup so AI models reference your business.</p></div>
          <div style={{ border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', padding: '24px', marginBottom: '16px' }}><h2 style={{ color: '#fff', fontSize: '17px', fontWeight: 700, margin: '0 0 8px 0' }}>Google Business Profile (GBP)</h2><p style={{ color: '#d1d5db', lineHeight: 1.7, margin: 0 }}>A free business listing managed through Google that appears in Google Maps and local search results. An optimized GBP is one of the most powerful local SEO assets a small business can have.</p></div>
          <div style={{ border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', padding: '24px', marginBottom: '16px' }}><h2 style={{ color: '#fff', fontSize: '17px', fontWeight: 700, margin: '0 0 8px 0' }}>Google AI Overviews</h2><p style={{ color: '#d1d5db', lineHeight: 1.7, margin: 0 }}>The AI-generated summary answers appearing at the top of Google search results. Businesses optimized for AEO and GEO have a higher chance of being cited inside AI Overviews.</p></div>
        </div>
        <div id='L' style={{ marginBottom: '56px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '16px', marginBottom: '24px' }}><span style={{ fontSize: '48px', fontWeight: 700, color: '#E8610A' }}>L</span><div style={{ flex: 1, height: '1px', background: '#E8610A', opacity: 0.3 }}></div></div>
          <div style={{ border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', padding: '24px', marginBottom: '16px' }}><h2 style={{ color: '#fff', fontSize: '17px', fontWeight: 700, margin: '0 0 8px 0' }}>Local Pack</h2><p style={{ color: '#d1d5db', lineHeight: 1.7, margin: 0 }}>The group of three local business listings appearing at the top of Google search results for location-based queries. Ranking in the Local Pack is one of the highest-impact goals for small business SEO.</p></div>
          <div style={{ border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', padding: '24px', marginBottom: '16px' }}><h2 style={{ color: '#fff', fontSize: '17px', fontWeight: 700, margin: '0 0 8px 0' }}>Local SEO</h2><p style={{ color: '#d1d5db', lineHeight: 1.7, margin: 0 }}>The practice of optimizing your online presence to rank higher in location-specific search results. Includes Google Business Profile optimization, citations, reviews, and locally-targeted content.</p></div>
          <div style={{ border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', padding: '24px', marginBottom: '16px' }}><h2 style={{ color: '#fff', fontSize: '17px', fontWeight: 700, margin: '0 0 8px 0' }}>Long-Tail Keyword</h2><p style={{ color: '#d1d5db', lineHeight: 1.7, margin: 0 }}>A specific multi-word search phrase with lower volume but higher purchase intent. Long-tail keywords are easier to rank for and often convert better than broad keywords.</p></div>
        </div>
        <div id='S' style={{ marginBottom: '56px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '16px', marginBottom: '24px' }}><span style={{ fontSize: '48px', fontWeight: 700, color: '#E8610A' }}>S</span><div style={{ flex: 1, height: '1px', background: '#E8610A', opacity: 0.3 }}></div></div>
          <div style={{ border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', padding: '24px', marginBottom: '16px' }}><h2 style={{ color: '#fff', fontSize: '17px', fontWeight: 700, margin: '0 0 8px 0' }}>Schema Markup</h2><p style={{ color: '#d1d5db', lineHeight: 1.7, margin: 0 }}>Structured data added to a web page in JSON-LD format that helps search engines understand your content. Essential for appearing in rich results and AI-generated answers.</p></div>
          <div style={{ border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', padding: '24px', marginBottom: '16px' }}><h2 style={{ color: '#fff', fontSize: '17px', fontWeight: 700, margin: '0 0 8px 0' }}>Search Engine Optimization (SEO)</h2><p style={{ color: '#d1d5db', lineHeight: 1.7, margin: 0 }}>The practice of improving your website and content so search engines rank it higher in organic results. SEO encompasses on-page, off-page, technical, and local strategies.</p></div>
          <div style={{ border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', padding: '24px', marginBottom: '16px' }}><h2 style={{ color: '#fff', fontSize: '17px', fontWeight: 700, margin: '0 0 8px 0' }}>Social Media Automation</h2><p style={{ color: '#d1d5db', lineHeight: 1.7, margin: 0 }}>The use of software to automatically create and publish social media posts on a schedule. Traffikora generates platform-specific posts for Facebook, Instagram, X, and more.</p></div>
        </div>
        <div id='Z' style={{ marginBottom: '56px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '16px', marginBottom: '24px' }}><span style={{ fontSize: '48px', fontWeight: 700, color: '#E8610A' }}>Z</span><div style={{ flex: 1, height: '1px', background: '#E8610A', opacity: 0.3 }}></div></div>
          <div style={{ border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', padding: '24px', marginBottom: '16px' }}><h2 style={{ color: '#fff', fontSize: '17px', fontWeight: 700, margin: '0 0 8px 0' }}>Zero-Click Search</h2><p style={{ color: '#d1d5db', lineHeight: 1.7, margin: 0 }}>A search result where the user gets their answer directly on the results page without clicking any link. Zero-click searches are increasing due to AI Overviews and featured snippets, making AEO strategy critical.</p></div>
        </div>
      </section>
      <section style={{ padding: '80px 24px', textAlign: 'center', background: 'linear-gradient(135deg, #E8610A 0%, #C84E06 100%)' }}>
        <h2 style={{ fontSize: 'clamp(28px, 5vw, 44px)', fontWeight: 700, color: '#fff', margin: '0 0 16px 0' }}>Put These Strategies to Work</h2>
        <p style={{ color: 'rgba(255,255,255,0.9)', fontSize: '18px', margin: '0 auto 32px', maxWidth: '500px' }}>Traffikora handles AEO, local SEO, social media, and blog automation -- all on autopilot.</p>
        <Link href='/signup' style={{ display: 'inline-block', background: '#fff', color: '#E8610A', fontWeight: 700, fontSize: '17px', padding: '16px 40px', borderRadius: '50px', textDecoration: 'none' }}>Start Free Trial</Link>
      </section>
    </main>
  )
}